sensor:
  - platform: template
    sensors:
      # Template sensor for values of energy bought (active_power < 0)
      energy_buy:
        device_class: power
        friendly_name: "Energy Buy"
        unit_of_measurement: 'W'
          #        state_class: measurement
        value_template: >-
          {% if states('sensor.on_grid_export_power')|float < 0 %}
            {{ states('sensor.on_grid_export_power')|float * -1 }}
          {% else %}
            {{ 0 }}
          {% endif %}
        availability_template: "{{ states('sensor.on_grid_export_power') not in ['unknown', 'unavailable'] }}"
      # Template sensor for values of energy sold (active_power > 0)
      energy_sell:
        device_class: power
        friendly_name: "Energy Sell"
        unit_of_measurement: 'W'
          #        state_class: measurement
        value_template: >-
          {% if states('sensor.on_grid_export_power')|float > 0 %}
            {{ states('sensor.on_grid_export_power')|float }}
          {% else %}
            {{ 0 }}
          {% endif %}
        availability_template: "{{ states('sensor.on_grid_export_power') not in ['unknown', 'unavailable'] }}"
      energy_battery_charge:
        device_class: power
        friendly_name: "Energy Battery Charge"
        unit_of_measurement: 'W'
        value_template: >-
          {% if states('sensor.battery_power')|float < 0 %}
            {{ states('sensor.battery_power')|float * -1 }}
          {% else %}
            {{ 0 }}
          {% endif %}
        availability_template: "{{ states('sensor.battery_power') not in ['unknown', 'unavailable'] }}"
      # Template sensor for values of energy sold (active_power > 0)
      energy_battery_discharge:
        device_class: power
        friendly_name: "Energy Battery Discharge"
        unit_of_measurement: 'W'
        value_template: >-
          {% if states('sensor.battery_power')|float > 0 %}
            {{ states('sensor.battery_power')|float }}
          {% else %}
            {{ 0 }}
          {% endif %}
        availability_template: "{{ states('sensor.battery_power') not in ['unknown', 'unavailable'] }}"
      house_consumption:
        device_class: power
        friendly_name: "House Consumption"
        unit_of_measurement: 'W'
        value_template: >-
          {{
            (states('sensor.pv_power')|float(0))
            + (states('sensor.energy_buy')|float(0))
            + (states('sensor.energy_battery_discharge')|float(0))
            - (states('sensor.energy_sell')|float(0))
            - (states('sensor.energy_battery_charge')|float(0))
          }}
        availability_template: >-
          {{ states('sensor.pv_power') not in ['unknown', 'unavailable']
             and states('sensor.energy_buy') not in ['unknown', 'unavailable']
             and states('sensor.energy_battery_discharge') not in ['unknown', 'unavailable']
             and states('sensor.energy_sell') not in ['unknown', 'unavailable']
             and states('sensor.energy_battery_charge') not in ['unknown', 'unavailable']
          }}

  # Sensor for Riemann sum of energy bought (W -> Wh)
  - platform: integration
    source: sensor.energy_buy
    name: energy_buy_sum
    unit_prefix: k
    round: 1
    method: left
  # Sensor for Riemann sum of energy sold (W -> Wh)
  - platform: integration
    source: sensor.energy_sell
    name: energy_sell_sum
    unit_prefix: k
    round: 1
    method: left
  - platform: integration
    source: sensor.energy_battery_charge
    name: energy_battery_charge_sum
    unit_prefix: k
    round: 1
    method: left
  # Sensor for Riemann sum of energy sold (W -> Wh)
  - platform: integration
    source: sensor.energy_battery_discharge
    name: energy_battery_discharge_sum
    unit_prefix: k
    round: 1
    method: left
  - platform: integration
    source: sensor.pv_power
    name: pv_power_sum
    unit_prefix: k
    round: 1
    method: left
  - platform: integration
    source: sensor.house_consumption
    name: house_consumption_sum
    unit_prefix: k
    round: 1
    method: left

utility_meter:
  energy_buy_daily:
    source: sensor.energy_buy_sum
    cycle: daily
  energy_buy_monthly:
    source: sensor.energy_buy_sum
    cycle: monthly
  energy_sell_daily:
    source: sensor.energy_sell_sum
    cycle: daily
  energy_sell_monthly:
    source: sensor.energy_sell_sum
    cycle: monthly
  house_consumption_daily:
    source: sensor.house_consumption_sum
    cycle: daily
  house_consumption_monthly:
    source: sensor.house_consumption_sum
    cycle: monthly

  energy_battery_charge_daily:
    source: sensor.energy_battery_charge_sum
    cycle: daily
  energy_battery_charge_monthly:
    source: sensor.energy_battery_charge_sum
    cycle: monthly
  energy_battery_discharge_daily:
    source: sensor.energy_battery_discharge_sum
    cycle: daily
  energy_battery_discharge_monthly:
    source: sensor.energy_battery_discharge_sum
    cycle: monthly

  pv_energy_daily:
    source: sensor.pv_power_sum
    cycle: daily
  pv_energy_monthly:
    source: sensor.pv_power_sum
    cycle: monthly
